name: rgb_lights
description: null
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
